### ISSUE TITLE
otherAccountNumberSpecified alltid False

### ISSUE THREAD

**Issue by kriswdue** [stenjo/SbankenToYNAB#14]
Hei!

Takk for et fantastisk verktøy!

Jeg oppdaget at når en setter includeReservedTransactions = False i api_settings.py, så slår denne kondisjonen ut linje 88 i sync_accounts, og ingen transaksjoner blir syncet som en følge:

`if transaction_item.get('isReservation') == True or transaction_item.get('otherAccountNumberSpecified') == False:
               continue`

Det ser ut til å være fordi otherAccountNumberSpecified alltid ser ut til å være False i transaksjonene mine fra Sbanken. så spørsmålet mitt er hvorfor det testes for otherAccountNumberSpecified, om det er endringer i Sbanken sitt api her?

**Comment by stenjo** [comment]
Takk for tips. Usikker her må jeg si. Må se litt på koden selv.
Kjekt at du synes dette er nyttig.

Kommer tilbake til deg.

Sten Johnsen
+47 91580061

30. aug. 2020 kl. 18:27 skrev kriswdue <notifications@github.com>:

﻿

Hei!

Takk for et fantastisk verktøy!

Jeg oppdaget at når en setter includeReservedTransactions = False i
api_settings.py, så slår denne kondisjonen ut linje 88 i sync_accounts, og
ingen transaksjoner blir syncet som en følge:

if transaction_item.get('isReservation') == True or
transaction_item.get('otherAccountNumberSpecified') == False: continue

Det ser ut til å være fordi otherAccountNumberSpecified alltid ser ut til å
være False i transaksjonene mine fra Sbanken. så spørsmålet mitt er hvorfor
det testes for otherAccountNumberSpecified, om det er endringer i Sbanken
sitt api her?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stenjo/SbankenToYNAB/issues/14>, or unsubscribe

**Comment by stenjo** [comment]
Må nok innrømme at dette er en feil - har ikke testet dette skikkelig og dermed glapp denne igjennom.
Bruker selv å ha med alle reserverte transaksjoner så jeg har på en måte heller ikke i praksis fått testet denne.
Vurderer å sette opp noen unit-tester etter hvert.

**Comment by stenjo** [comment]
Ser at det nok er en bug det du har funnet. 
Transaksjoner mellom kontoer i SBanken har flagget otherAccountNumberSpecified satt til True. Bruker det for å identifisere og matche transaksjoner mellom to kontoer sånn at du ikke trenger å gjøre den jobben manuelt. Har åpenbart ikke testet tilstrekkelig i kombinasjon med å ikke synke reserverte transaksjoner.
Skal se på å få fikset dette.

**Comment by stenjo** [comment]
Hele sjekken er nå kommentert bort. Greier ikke å finne eksempler på at otherAccountNumberSpecified er True i et års logg med transaksjoner i en konto, så tror vi kan se bort i fra denne ja.
